name: 'Check Email of Commit Author and Committer'
description: 'Checks the email of the commit author and committer'
inputs:
  author_email_domain:
    description: 'domain of the author\'s emails'
    required: true
  committer_email_domain:
    description: 'domain of the committer\'s emails'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  error_on_fail:
    description: 'Decides if action should throw an error on invalid email or not'
    required: false
    default: 'true'
outputs:
  is_valid:
    description: 'returns to result whether true or false'

runs:
  using: node16
  main: dist/index.js
